const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const fs=require('fs');const assert=require('assert/strict');const out=require('path').resolve('outputs/v3-verification-2026-09-08');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const results=[];const errors=[];page.on('pageerror',e=>errors.push(e.message));const shot=async n=>{await page.waitForTimeout(500);await page.screenshot({path:out+'/'+n+'.png',fullPage:true})};const go=async q=>{await page.goto('http://127.0.0.1:5183/'+q);await page.waitForLoadState('networkidle')};const check=async n=>{assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,n+' horizontal overflow');results.push(n)};
await go('?page=home&preview=browser');await page.locator('.search-field input').fill('Айдана');assert.equal(await page.locator('.person-card').count(),1);await page.locator('.person-card').click();await page.locator('.profile-head').waitFor();assert.match(await page.locator('h1').innerText(),/Айдана/);await shot('desktop-profile');results.push('Live global search -> profile');
for(const kind of ['teachers','laureates','veterans']){await go('?page='+kind+'&preview=browser');assert.equal(await page.locator('.person-card').count(),kind==='veterans'?5:6);await page.locator('.person-card').first().click();await page.locator('.profile-head').waitFor();results.push(kind+' live collection -> profile')}
await go('u/apply?preview=browser');await page.getByPlaceholder('Айдос Серикулы Жумабеков').fill('QA V3 — do not publish');await page.locator('select').first().selectOption('mit');let posted;await page.route('**/api/submissions',route=>{posted=route.request().postDataJSON();return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'QA: сервер временно недоступен'})})});await page.getByRole('button',{name:'Отправить',exact:false}).click();await page.getByRole('alert').waitFor();assert.equal(await page.getByPlaceholder('Айдос Серикулы Жумабеков').inputValue(),'QA V3 — do not publish');assert.equal(posted.fac,'mit');await shot('application-error');results.push('Application API503 preserves fields; POST intercepted, no DB write');await page.unroute('**/api/submissions');
await page.setViewportSize({width:390,height:844});await go('u/apply?preview=browser');await shot('mobile-apply');await check('Mobile apply');await go('?page=access&preview=browser');await shot('mobile-access');await check('Mobile access');
await page.setViewportSize({width:1440,height:1000});await go('?page=access&preview=browser');await page.route('**/api/auth/login',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({token:'qa-browser-only',role:'admin',username:'qa',fac:''})}));await page.route('**/api/auth/me',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({role:'admin',username:'qa',fac:''})}));await page.route('**/api/moderators',r=>r.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.route('**/api/submissions',r=>r.fulfill({status:200,contentType:'application/json',body:'[]'}));let logout=false;await page.route('**/api/auth/logout',r=>{logout=true;return r.fulfill({status:200,contentType:'application/json',body:'{}'})});await page.locator('input[autocomplete=username]').fill('qa');await page.locator('input[type=password]').fill('qa');await page.locator('input[type=password]').press('Enter');await page.waitForURL('**page=admin*');await shot('staff-admin-mocked');await page.getByRole('button',{name:'Выйти',exact:true}).click();await page.waitForTimeout(250);assert(logout);assert.equal(await page.evaluate(()=>localStorage.getItem('alumni-staff-session')),null);await page.goBack();assert.equal(await page.locator('input[type=password]').count(),1);results.push('Mocked admin login/redirect/logout/history guard; real backend auth not exercised');
await page.setViewportSize({width:1080,height:1920});await go('?preview=kiosk&page=home');await page.getByRole('button',{name:'Найти выпускника',exact:true}).click();await page.getByRole('button',{name:'ҚАЗ',exact:true}).click();await page.getByRole('button',{name:'Ә',exact:true}).click();await shot('portrait-keyboard');assert.equal(await page.locator('input').inputValue(),'Ә');await page.getByRole('button',{name:'Главная',exact:true}).click();await page.getByRole('button',{name:'Ә',exact:true}).waitFor({state:'hidden'});await check('Kiosk Home closes KZ keyboard');
await go('?preview=kiosk&page=teachers');await page.locator('.person-card').first().click();console.log('Waiting real 60-second idle timer');await page.waitForTimeout(31000);console.log('Idle timer halfway');await page.waitForTimeout(31000);await page.getByRole('button',{name:/Коснитесь/}).waitFor();await shot('portrait-idle');await page.getByRole('button',{name:/Коснитесь/}).click();await page.locator('.faculty-grid').waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('alumni-staff-session')),null);results.push('Real 60s idle resets to home + attract, tap dismisses');
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/flows.json',JSON.stringify({results,errors},null,2));console.log(results);await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
